### ISSUE TITLE
YoCool-v1.1.5 申请出刀无响应

### ISSUE THREAD

**Issue by V1046-R** [A-kirami/YoCool#14]
群聊内「申请出刀」bot无响应，

在网页版点击申请出刀会弹窗 [ server error ] 。

回滚到1.1.3版本（yobot 3.6.8 ) 无此问题。

不知道是不是我个别情况。

**Comment by A-kirami** [comment]
使用的yocool为便携版还是插件版？

**Comment by V1046-R** [comment]
> 使用的yocool为便携版还是插件版？

已美化的便携版。

**Comment by V1046-R** [comment]
> 使用的yocool为便携版还是插件版？

刚刚使用了v1.1.6版本，已经没有这个问题，感谢您的回复。
