### ISSUE TITLE
yocool适配yobot3.6.4-rc2的用户信息问题

### ISSUE THREAD

**Issue by elysiuma** [A-kirami/YoCool#2]
新版yobot中用户信息修改的函数从yobot_user_info_nickname(qqid)改为了yobot_user_info_api(qqid)，在yocool的user-info.html中
                axios.put('{{ url_for("yobot_user_info_nickname", qqid=user.qqid) }}',{nickname: thisvue.nickname}).then(function (res) {
应改为：
                axios.put('{{ url_for("yobot_user_info_api", qqid=user.qqid) }}',{nickname: thisvue.nickname}).then(function (res) {

**Comment by A-kirami** [comment]
感谢反馈，已更新到wiki
