### ISSUE TITLE
首页UI显示问题

### ISSUE THREAD

**Issue by Cathgao** [A-kirami/YoCool#7]
首页工会名字过长时，文字会超出按钮长度
浏览器为 EDGE 86.0.622.48 (官方内部版本) (64 位)，安卓chrome 86.0.4240.99
已强制刷新浏览器缓存

![QQ截图20201021092829](https://user-images.githubusercontent.com/21031564/96662101-345a3200-1380-11eb-89e4-93af8b1055ff.png)

**Comment by A-kirami** [comment]
因为强制统一了按钮宽度的缘故，现在可以手动将user.html中第94行的style="width: 200px;"修改，如果需要更大的宽度，请将200调整为更大的数值（今后的版本更新中可能解决这个问题

**Comment by Cathgao** [comment]
能自动调整大小就最好了。感谢关注
